### ISSUE TITLE
Doesn't Work with Media Temple Grid-Service Servers

### ISSUE THREAD

**Issue by grayghostvisuals** [scttnlsn/dandelion#41]
I've tried many methods with no luck.

Due to the way the (gs) Grid-Service Server is configured, they use symlinks to connect certain directories.

The `.home` directory has a symlink, which navigates two levels up and places you in `/home/XXXXXX/domains`. This symlink exists to maintain a connection between certain (gs) Grid-Service Server services.

Here are all the paths I've tried with no such luck using `dandelion deploy`. I've also included my `dandelion.yml` settings file.

**Try #1 - Full Root Path**
`nfs/cXX/home/mnt/home/XXXXXX/domains/sub-domain.grayghostvisuals.com/html/`

Result:
This puts everything in a "home" directory within my ".home" directory

**Try #2**
`home/XXXXXX/domains/sub-domain.grayghostvisuals.com/html/`

Result:
This puts everything in a "home" directory within my ".home" directory

**Try #3**
`home/XXXXXX/users/.home/domains/sub-domain.grayghostvisuals.com/html/`

Result:
This puts everything in a "home" directory within my ".home" directory
### `dandelion.yml`

``` yaml
# Required
# --------

scheme: sftp
host: sXXXXXX.gridserver.com
username: XXXXXXXXXXX
password: XXXXXXXXXXX

# Optional
# --------
# Remote path
path: home/XXXXXX/users/.home/domains/sub-domain.grayghostvisuals.com/html/
port: 22

# These files (from Git) will not be uploaded during a deploy
exclude:
    - .gitignore
    - dandelion.yml
    - new0513/
```
