### ISSUE TITLE
Deploying corrupts image files

### ISSUE THREAD

**Issue by nev7n** [scttnlsn/dandelion#91]
When delpoying over sftp changed image files are uploaded but corrupted in the process.  My dandelion.yml looks like this:

``` yaml
adapter: sftp
host: xxxx.co.uk
username: xxxxx
password: xxxxx
path: /home/xxxx

exclude:
    - .gitignore
    - dandelion.yml
    - folder/
```

My client machine is Windows 8.1 with Ruby 1.9.3, Server is CENTOS 6.5 x86_64.  

It looks like it's treating binary files as text and converting line breaks.  An example corrupted file is 926 bytes instead of 921 bytes and I can see extra '0x0D' characters inserted before '0x0A'.

Otherwise it all works a treat.
