### ISSUE TITLE
Multiple Deploy Destinations 

### ISSUE THREAD

**Issue by whitehat101** [scttnlsn/dandelion#96]
Have you thought about supporting multiple deploy destinations? I'd like to have a "production" and a "staging" deploy that share common settings (exclude, additional) but have different credentials.

Maybe, have the config as it is now be the "default", and if a deploy name is given, then merge that hash, into the root.

``` yaml
adapter: sftp
path: path/to/deployment

production:
  host: example1.com
  username: user1
  password: pass1

staging:
  host: example2.com
  username: user2
  password: pass2

  additional:
    - config/staging-auth.yml

exclude:
  - .gitignore
  - dandelion.yml
  - dir/

additional:
  - config/auth.yml

```

Really nice Gem, by the way.
